In [11]:
import pandas as pd
import numpy as np

In [ ]:
chem_df = pd.read_csv("Etalons_All_Bases_new.csv", sep=";", header=None)

chem_dicts = []
for _, row in chem_df.iterrows():
    sample = row[0]
    chem_data = {row[i]: float(str(row[i+2]).replace(',', '.')) for i in range(1, len(row)-2, 3)}
    chem_dicts.append({"Sample": sample, **chem_data})

chem_df_clean = pd.DataFrame(chem_dicts)

In [13]:
print(chem_df_clean)

    Sample    C   Si    Mn    Cr    Ni   Mo   Ti   Cu   Al  ...   Tl   Nd  \
0       24  0.0  0.0  10.6  13.8   1.2  0.0  0.0  1.0  0.0  ...  0.0  0.0
1       79  0.0  0.7   0.0  39.0  55.7  0.5  0.0  0.0  3.1  ...  0.0  0.0
2      147  0.0  0.2  10.1  14.4   1.1  0.0  0.0  1.6  0.0  ...  0.0  0.0
3      361  1.6  0.6   0.0   9.2   0.6  0.9  0.0  0.0  0.0  ...  0.0  0.0
4      362  1.6  0.4   0.2  10.4   0.4  0.6  0.0  0.0  0.0  ...  0.0  0.0
..     ...  ...  ...   ...   ...   ...  ...  ...  ...  ...  ...  ...  ...
390   znfe  0.0  0.0   0.0   0.0   0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0
391   znsn  0.0  0.0   0.0   0.0   0.0  0.0  0.0  3.7  0.4  ...  0.0  0.0
392  zr100  0.0  0.0   0.0   0.0   0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0
393    zr2  0.0  0.0   0.0   0.3   0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0
394   zrnb  0.0  0.0   0.0   0.0   0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0

      La    Y   Gd   Ge   Ta   Ce    B   Hf
0    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
1    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
4    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
..   ...  ...  ...  ...  ...  ...  ...  ...
390  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
391  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
392  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
393  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
394  0.0  0.0  0.0  0.0  0.2  0.0  0.0  0.0

[395 rows x 41 columns]

In [ ]:
features_df = pd.read_csv("post_componator_spectra.csv")

In [15]:
print(features_df)

         Device Material  Temperature  Sample          0          1  \
0      SN_25470     AAZn          244     zn5 -48.500910 -22.718463
1      SN_25470     AAZn          244     zn7 -47.418066 -27.599992
2      SN_25470     AAZn          245   zn511 -56.325843 -53.052148
3      SN_25470     AAZn          245   zn512 -56.536547 -46.005092
4      SN_25470     AAZn          246     zn3 -50.195876   3.452653
...         ...      ...          ...     ...        ...        ...
11994  SN_25480       Ti          308  htb081 -23.853054 -12.236780
11995  SN_25480       Ti          308   bt3-1 -23.331600 -11.247968
11996  SN_25480       Ti          308     g43 -33.908710 -22.602477
11997  SN_25480       Ti          309   bt3-1 -28.898700 -18.615578
11998  SN_25480       Ti          309  htb081 -24.586143 -13.397360

                2          3          4          5  ...       246       247  \
0       85.996946 -44.628783 -25.506272  -7.119218  ...  0.784656  0.028412
1      101.990461 -46.837206 -40.263752 -13.110539  ...  0.465147  0.029212
2       56.627529 -54.472887 -20.726875  -6.979564  ...  0.587716  0.019388
3       63.913441 -55.151212 -22.825680  -8.557960  ...  0.598321 -0.425600
4      134.483882 -48.686404 -39.528888 -11.376974  ...  0.174988  0.357433
...           ...        ...        ...        ...  ...       ...       ...
11994   -5.305276  38.381366  -3.724170  -3.255904  ... -0.077693  0.015833
11995   -3.322359  54.776268  -7.589793  -3.024065  ... -0.079930 -0.171229
11996   -8.639030  35.318537  -4.394314  -4.374844  ... -0.144328 -0.129035
11997   -6.122482  48.552206  -7.033098  -3.814686  ...  0.060111 -0.077206
11998   -5.610924  38.110754  -3.609525  -3.177987  ... -0.089118  0.057636

            248       249       250       251       252       253       254  \
0      0.696659  0.403670 -0.299282  0.163117  0.220954  0.193518  0.151145
1      0.333475  0.214408 -0.440832  0.183957  0.217866 -0.126114 -0.045469
2      0.496428  0.473894 -0.224694  0.184021  0.068394 -0.020320  0.094210
3      0.356704  0.477834 -0.233673  0.052476  0.265061 -0.113109  0.173927
4     -0.215756  0.990983 -0.174862 -0.108669 -0.476497 -0.160260 -0.065466
...         ...       ...       ...       ...       ...       ...       ...
11994  0.020785 -0.150904  0.011506  0.287451 -0.021866  0.191860 -0.217155
11995  0.009834  0.087144  0.082298 -0.129266 -0.084830 -0.112484 -0.050641
11996 -0.037674 -0.008638  0.039256  0.081212  0.075668 -0.054750 -0.016578
11997 -0.067803  0.048359  0.069162 -0.113226 -0.077990 -0.046029 -0.083419
11998 -0.013890 -0.128985 -0.007630  0.277232 -0.060576  0.157351 -0.262560

            255
0     -0.009046
1     -0.378214
2     -0.061301
3     -0.288467
4      0.540504
...         ...
11994 -0.032245
11995 -0.043956
11996  0.011757
11997  0.046864
11998 -0.007917

[11999 rows x 260 columns]

In [ ]:
merged_df = pd.merge(features_df, chem_df_clean, on="Sample", how="left")
merged_df = merged_df.dropna()

In [17]:
print(merged_df)

         Device Material  Temperature  Sample          0          1  \
0      SN_25470     AAZn          244     zn5 -48.500910 -22.718463
1      SN_25470     AAZn          244     zn7 -47.418066 -27.599992
2      SN_25470     AAZn          245   zn511 -56.325843 -53.052148
3      SN_25470     AAZn          245   zn512 -56.536547 -46.005092
4      SN_25470     AAZn          246     zn3 -50.195876   3.452653
...         ...      ...          ...     ...        ...        ...
11994  SN_25480       Ti          308  htb081 -23.853054 -12.236780
11995  SN_25480       Ti          308   bt3-1 -23.331600 -11.247968
11996  SN_25480       Ti          308     g43 -33.908710 -22.602477
11997  SN_25480       Ti          309   bt3-1 -28.898700 -18.615578
11998  SN_25480       Ti          309  htb081 -24.586143 -13.397360

                2          3          4          5  ...   Tl   Nd   La    Y  \
0       85.996946 -44.628783 -25.506272  -7.119218  ...  0.0  0.0  0.0  0.0
1      101.990461 -46.837206 -40.263752 -13.110539  ...  0.0  0.0  0.0  0.0
2       56.627529 -54.472887 -20.726875  -6.979564  ...  0.0  0.0  0.0  0.0
3       63.913441 -55.151212 -22.825680  -8.557960  ...  0.0  0.0  0.0  0.0
4      134.483882 -48.686404 -39.528888 -11.376974  ...  0.0  0.0  0.0  0.0
...           ...        ...        ...        ...  ...  ...  ...  ...  ...
11994   -5.305276  38.381366  -3.724170  -3.255904  ...  0.0  0.0  0.0  0.0
11995   -3.322359  54.776268  -7.589793  -3.024065  ...  0.0  0.0  0.0  0.0
11996   -8.639030  35.318537  -4.394314  -4.374844  ...  0.0  0.0  0.0  0.0
11997   -6.122482  48.552206  -7.033098  -3.814686  ...  0.0  0.0  0.0  0.0
11998   -5.610924  38.110754  -3.609525  -3.177987  ...  0.0  0.0  0.0  0.0

        Gd   Ge   Ta   Ce    B   Hf
0      0.0  0.0  0.0  0.0  0.0  0.0
1      0.0  0.0  0.0  0.0  0.0  0.0
2      0.0  0.0  0.0  0.0  0.0  0.0
3      0.0  0.0  0.0  0.0  0.0  0.0
4      0.0  0.0  0.0  0.0  0.0  0.0
...    ...  ...  ...  ...  ...  ...
11994  0.0  0.0  0.0  0.0  0.0  0.0
11995  0.0  0.0  0.0  0.0  0.0  0.0
11996  0.0  0.0  0.0  0.0  0.0  0.0
11997  0.0  0.0  0.0  0.0  0.0  0.0
11998  0.0  0.0  0.0  0.0  0.0  0.0

[8365 rows x 300 columns]

In [ ]:
merged_df.to_csv("final_dataset.csv", index=False)

In [19]:
chemicas = ['C','Si','Mn','Cr','Ni','Mo','Ti','Cu','Al','V','Nb','Co','W','Fe','Zr','Be','Sb','Mg','Zn','S','P','Pb','Sn','Cd','Ca','Bi','Ag','Ga','Sc','Au','Tl','Nd','La','Y','Gd','Ge','Ta','Ce','B','Hf']
np.savetxt("/tmp/check.txt", merged_df[chemicas].values)